name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPENDENCIES_CACHE: cache-node-modules

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/use-cache
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: pnpm install
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/use-cache
      - run: pnpm run build
      - uses: vimtor/action-zip@v1.2
        with:
          files: dist/
          dest: evwrite_annotation_flow.zip
      - uses: actions/upload-artifact@v4
        with:
          name: evwrite_annotation_flow
          path: ${{ github.workspace }}/evwrite_annotation_flow.zip
  test:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/use-cache
      - run: pnpm run test:unit
  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/use-cache
      - run: pnpm run lint
